import { NextRequest, NextResponse } from "next/server";

const RESEND_API_URL = "https://api.resend.com/emails";
const DEFAULT_TO_EMAIL = "jahanzaib@hyperlogic.studio";
const DEFAULT_FROM_EMAIL = "Jahanzaib Portfolio <onboarding@resend.dev>";
const SOURCE_SITE = "jahanzaibshaikh.dev";

function cleanText(value: unknown, maxLength: number) {
  if (typeof value !== "string") return "";
  return value.trim().slice(0, maxLength);
}

function isValidEmail(email: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function createEmailHtml({
  name,
  email,
  subject,
  message,
}: {
  name: string;
  email: string;
  subject: string;
  message: string;
}) {
  const safeName = escapeHtml(name);
  const safeEmail = escapeHtml(email);
  const safeSubject = escapeHtml(subject || "No subject provided");
  const safeMessage = escapeHtml(message).replace(/\n/g, "<br />");

  return `
    <div style="margin:0;padding:0;background:#f4f4f0;font-family:Inter,Arial,sans-serif;color:#151515;">
      <div style="max-width:680px;margin:0 auto;padding:32px 18px;">
        <div style="border-radius:24px;background:#ffffff;border:1px solid #e7e2d8;overflow:hidden;box-shadow:0 24px 70px rgba(20,20,20,0.08);">
          <div style="background:#0f1215;color:#eaff00;padding:22px 26px;">
            <p style="margin:0 0 6px;font-size:12px;letter-spacing:0.16em;text-transform:uppercase;font-weight:800;">New portfolio message</p>
            <h1 style="margin:0;color:#ffffff;font-size:24px;line-height:1.25;">Message received from ${SOURCE_SITE}</h1>
          </div>
          <div style="padding:26px;">
            <div style="display:grid;gap:14px;margin-bottom:22px;">
              <div style="padding:14px 16px;border-radius:16px;background:#f8f7f2;border:1px solid #ece7dc;">
                <p style="margin:0 0 4px;font-size:11px;letter-spacing:0.12em;text-transform:uppercase;color:#777;font-weight:800;">Name</p>
                <p style="margin:0;font-size:16px;font-weight:700;">${safeName}</p>
              </div>
              <div style="padding:14px 16px;border-radius:16px;background:#f8f7f2;border:1px solid #ece7dc;">
                <p style="margin:0 0 4px;font-size:11px;letter-spacing:0.12em;text-transform:uppercase;color:#777;font-weight:800;">Email</p>
                <p style="margin:0;font-size:16px;font-weight:700;"><a href="mailto:${safeEmail}" style="color:#111;text-decoration:none;">${safeEmail}</a></p>
              </div>
              <div style="padding:14px 16px;border-radius:16px;background:#f8f7f2;border:1px solid #ece7dc;">
                <p style="margin:0 0 4px;font-size:11px;letter-spacing:0.12em;text-transform:uppercase;color:#777;font-weight:800;">Subject</p>
                <p style="margin:0;font-size:16px;font-weight:700;">${safeSubject}</p>
              </div>
            </div>
            <div style="padding:18px;border-radius:18px;background:#111417;color:#f7f7f2;border:1px solid #25282c;">
              <p style="margin:0 0 10px;font-size:11px;letter-spacing:0.12em;text-transform:uppercase;color:#eaff00;font-weight:800;">Message</p>
              <div style="font-size:15px;line-height:1.75;color:#f2f2ea;">${safeMessage}</div>
            </div>
            <p style="margin:22px 0 0;color:#777;font-size:12px;line-height:1.6;">This alert was generated by the contact form on ${SOURCE_SITE}. Reply directly to this email to contact the sender.</p>
          </div>
        </div>
      </div>
    </div>
  `;
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const name = cleanText(body.name, 80);
    const email = cleanText(body.email, 160).toLowerCase();
    const subject = cleanText(body.subject, 140) || "Portfolio contact message";
    const message = cleanText(body.message, 5000);

    if (!name || !email || !message) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    if (!isValidEmail(email)) {
      return NextResponse.json({ error: "Invalid email address" }, { status: 400 });
    }

    const resendApiKey = process.env.RESEND_API_KEY;

    if (!resendApiKey) {
      console.error("RESEND_API_KEY is not configured");
      return NextResponse.json({ error: "Email service is not configured" }, { status: 500 });
    }

    const toEmail = process.env.CONTACT_TO_EMAIL || DEFAULT_TO_EMAIL;
    const fromEmail = process.env.CONTACT_FROM_EMAIL || DEFAULT_FROM_EMAIL;
    const emailSubject = `[${SOURCE_SITE}] ${subject}`;
    const textBody = [
      `New message from ${SOURCE_SITE}`,
      "",
      `Name: ${name}`,
      `Email: ${email}`,
      `Subject: ${subject}`,
      "",
      "Message:",
      message,
    ].join("\n");

    const resendResponse = await fetch(RESEND_API_URL, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${resendApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: fromEmail,
        to: [toEmail],
        reply_to: email,
        subject: emailSubject,
        text: textBody,
        html: createEmailHtml({ name, email, subject, message }),
      }),
    });

    if (!resendResponse.ok) {
      const errorText = await resendResponse.text();
      console.error("Resend email failed:", errorText);
      return NextResponse.json({ error: "Failed to send message" }, { status: 502 });
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Contact route error:", error);
    return NextResponse.json({ error: "Server error" }, { status: 500 });
  }
}
